"""EP.02 콘티·프롬프트 생성. python build_prompts.py (episodes/ep02 에서 실행)"""
files = {}
files['conti.md'] = """# EP.02 「일어나지 않을 일까지 미리 겪을 수 있는 초능력」

주인공 두부. 소품: 몸만 한 테라코타 배낭 `#C77B3F` (터질 듯 불룩, 덮개·어깨끈). 7컷에만 망토. 표지 + 7컷.

| 컷 | 장면 | 내레이션 | 속마음·대사(합성) |
|---|---|---|---|
| 표지 | 배낭을 멘 두부가 히어로 포즈(손가락 하늘로)를 취하고 있지만 걱정으로 덜덜 떨고 있음 — 떨림선, 무릎 모임 | 제목 | 감정: 땀방울 + 떨림선 |
| 1 | 배낭 두부가 공중에 떠서 가부좌 명상 (닥터 스트레인지 인피니티 워 타이탄 장면: 눈 감음, 가슴에 초록 타임스톤, 손으로 인을 맺음, 초록 실선이 손·머리 주위를 감돎, 머리가 사방으로 빠르게 흔들려 잔상). 주위에 불운 장면 5개가 각각 다른 단색 원형 비네트로 떠 있음 (비 맞기 / 버스 놓치기 / 넘어지기 / 폰 액정 깨짐 / 아이스크림 떨어뜨림) | 우리는 아직 일어나지도 않은 일들을 / 상상으로 미리 겪을 수 있다. | 감정: 반짝이 |
| 2 | 비. 흠뻑 젖어 축 처진 탱자. 두부는 배낭을 바닥에 내려놓고 팔을 어깨까지 넣어 뒤지다 우산을 꺼내는 중. 배낭 주위 바닥에 이미 꺼낸 물건들 (반창고, 충전기, 휴지, 간식, 물병, 수첩, 장갑, 양말, 손전등, 반짇고리) | 별명이 보부상인 우리는 / 항상 가방 속에 아이템이 가득하고 | 감정: 탱자 머리 위 하트 |
| 3 | 배낭 두부가 콧노래 부르며 태연히 걸어감. 뒤로 떨어져 박히는 바위, 코앞을 스치는 칼, 옆에서 터지는 폭발 — 전부 빗나감 | 이미 수만 개의 미래를 보고왔기 때문에 / 어떤 상황에도 대처를 할 수 있지만... | 감정: 음표 |
| 4 | **공유 컷.** 바닥에 웅크려 앉아 폰을 얼굴 앞에 들고 화면 위로 눈만 내놓은 두부. 화면에 "ㅇㅇ" 답장 하나. 옆에 배낭 | 오지도 않을 미래들 때문에 / 하루에도 몇 번 씩 지옥과 천국을 오간다! | 폰 화면: ㅇㅇ · 감정: 먹구름 (편당 1회) |
| 5 | 여행 가는 날, 쨍한 해. 하와이안 셔츠 입은 미숙·덕수·콩은 신남. 두부만 패딩에 배낭에 우산까지 쓰고 녹초 | 때로는 걱정이 과해 / 준비만으로 지치기도 하고 | 감정: 세로 그늘선 |
| 6 | 밤. 이불을 코까지 덮은 두부가 눈을 꽉 찡그리고 덜덜 떪. 위에 꿈 구름(꼬리 없음): 밤톨이 핑크 고양이와 팔짱 끼고 걸어감, 사이에 하트 | 눈을 감기 전에는 망상에 시달리고 / 눈을 감으면 개꿈같은 악몽에 시달리지만 | 감정: 눈물 한 방울 + 이불 떨림선 |
| 7 | 이마에 부적, 갑옷, 방패, 쉴드(반투명 구), 테라코타 망토, 배낭까지 갖추고 편의점으로 출발하는 두부. 머리 위 라벨 "편의점 가는 길" | 깜짝 놀라는 하루는 싫어. / 나는 항상 준비하고 있을래. | 라벨: 편의점 가는 길 · CTA: 당신 옆의 초능력자를 태그해 주세요 · 감정: 없음 (눈 일자) |

톤: 1–3 밝음 → 4–6 저채도 → 7 망토 + 포인트 컬러 복귀. 감정 기호는 컷마다 다르게(표지 땀방울 · 1 반짝이 · 2 하트 · 3 음표 · 4 먹구름 · 5 세로 그늘선 · 6 눈물). 참조: 두부·탱자·미숙·덕수·콩·밤톨 시트, 고양이 3인조 시트, `ref/lineup-*.png`, 깜자 2장. 프롬프트는 `build_prompts.py`가 만든다.
"""
HEADER = """Reference images:
- The FIRST image is the CHARACTER SHEET of Dubu, a cream-colored sheep. Reproduce this exact character design.
- Further character sheets / a size lineup may follow; the lineup image shows their relative sizes.
- The last two images are STYLE references only (the Korean instatoon dog "Kkamja"): copy its drawing grammar — wobbly hand-drawn black outline of uneven thickness, flat colors, no shading, simple emotion symbols (sweat drop, sparkles, tiny rain cloud, hearts) — but NOT its character or color.

Dubu design:
- cream #F6F2E6 body, ONE solid color everywhere including the face. No markings, no darker face, no inner-ear color
- 2-head-tall potato body with a soft cloud-shaped fluffy outline, stubby limbs, tiny tail, two small rounded ears sticking out sideways
- face: two small black dot eyes set wide apart, one small dark dot nose, NO MOUTH, NO BLUSH, no eyelashes

Prop of this episode, THE BACKPACK: a big terracotta #C77B3F backpack, nearly as tall as Dubu's whole body, round and overstuffed so its flap barely closes, with two shoulder straps and a small handle on top. Drawn flat, bold, simple, with the same wobbly outline. When Dubu WEARS it, both straps go over her shoulders and the bag sticks out behind and above her back.

"""
END = "\nNo text, no letters, no speech bubbles, no captions. Plain white background.\n"
cuts = {}
cuts['cover'] = "Draw ONE full-body Dubu, front view, wearing THE BACKPACK, in a hero pose: feet apart, chest out, one arm raised high pointing an index finger up into the air, the other arm on the hip. BUT she is scared and trembling at the same time: her dot eyes are slightly bigger round dots, the outline of her body and of the raised arm is drawn extra jittery and wobbly, short parallel vibration lines are drawn on both sides of her body and beside the raised arm, her knees turn inward and knock together, and three or four sweat drops fly off her head. No sparkles. Character in the lower 60% of the image, the upper 40% must be completely empty white for a title." + END
cuts['cut1'] = "Scene: Dubu, wearing THE BACKPACK, floats in mid-air a little above the ground, sitting cross-legged in a lotus meditation pose exactly like Doctor Strange viewing thousands of possible futures with the Time Stone: eyes closed (two small closed downward arcs), both stubby arms held up in front of her chest with the hands turned outward as if weaving a spell, a small glowing green #7FE3A0 circle on her chest, thin glowing green spiral threads and rings swirling around her hands and around her head, and her head drawn with two faint semi-transparent ghost copies offset to the left and right (afterimages) to show it darting rapidly from side to side. A few tiny sparkles around her. Floating around her in a loose ring, five small round vignettes, each a flat circle tinted in ONE different pastel color (pale red, pale blue, pale yellow, pale purple, pale green) with its tiny scene drawn in darker tones of that same single color, like monochrome stickers: (1) a tiny Dubu with no umbrella under a pouring rain cloud, (2) a tiny Dubu running after a bus that is driving away, (3) a tiny Dubu tripping and falling flat on her face, (4) a tiny Dubu holding a phone with a cracked screen, (5) a tiny Dubu looking down at an ice-cream scoop splattered on the ground. Everything in the lower 65% of the image, the upper 35% empty white." + END
cuts['cut2'] = """Additional character: Tangja, a yellow #F5E08C duck, ONE solid color, flat orange #F0A83A bill and webbed feet, stubby wing arms, small feather tuft on top of the head, dot eyes, no mouth (see her sheet and the lineup). Same height as Dubu.
Scene: it is raining — many thin diagonal gray rain lines fall over the whole scene (rain lines only; the background stays plain white, no cloud). On the right, Tangja stands drenched and drooping: feather tuft flattened, wings hanging limp, a few water drops dripping off her, dot eyes looking at Dubu, and one small heart floating above her head. On the left, Dubu has taken THE BACKPACK off and set it on the ground in front of her; she is bent over it digging inside with both arms in up to the shoulders, and is just pulling out a folded pale blue umbrella. All around the backpack, items she has already dug out lie scattered on the ground: a box of band-aids, a phone charger with a coiled cable, a pack of tissues, a snack bar, a water bottle, a small notebook, a pair of gloves, a pair of socks, a flashlight, a small sewing kit — all small, simply drawn, flat colors. Both characters full body, in the lower 60% of the image; the upper 40% empty white.""" + END
cuts['cut3'] = "Scene: Dubu, wearing THE BACKPACK, walks calmly from left to right in three-quarter view with a relaxed stride, eyes as closed happy upward arcs, one small black musical note floating beside her head as if she is humming. Dangers miss her all at once and she does not react to any of them: a big gray boulder has just crashed onto the ground one step behind her (small impact lines and two dust puffs), a flying knife (simple silver blade, brown handle) shoots past right in front of her nose with a few motion lines, and a small cartoon explosion (a flat orange and yellow spiky burst with a puff of gray smoke) goes off on the ground a little to her left. She just keeps walking. Everything in the lower 60% of the image, the upper 40% empty white." + END
cuts['cut4'] = "Scene: Dubu sits on the floor hunched over with her knees drawn up, holding a smartphone up in front of her face with both hands so that the screen faces the viewer; only her ears and her two dot eyes peek over the top edge of the phone. The phone is drawn large and simple: a dark rounded rectangle with a plain pale, completely empty screen (no icons, no lines). THE BACKPACK sits on the floor beside her. One tiny gray rain cloud floats above her head. Body slightly shrunk. Muted, slightly desaturated colors. Character in the lower 55% of the image, the upper 45% empty white." + END
cuts['cut5'] = """Additional characters (see their sheets and the lineup image, which shows their relative sizes):
- Misook, a soft orange #F6CA9E fox: ONE solid color everywhere, large pointed triangular ears, one big bushy tail curling up beside the body, dot eyes, no mouth. Slightly taller than Dubu.
- Deoksu, a tan #EACEAA deer: ONE solid color, small upright ears, a pair of simple two-prong antlers in a darker brown exactly as in his sheet, dot eyes, no mouth. The tallest of the group.
- Kong, a light gray #DED6DA mouse: ONE solid color, two BIG round ears on top of the head, one thin curly tail, dot eyes, no mouth. Same height as Dubu.
Scene: a family leaving for a summer trip on a bright sunny day. A simple flat yellow sun with short rays in the upper right corner (the only thing in the sky). On the left, Misook, Deoksu and Kong stand close together, cheerful, eyes as closed upward arcs, each wearing a short-sleeve Hawaiian shirt with a flat simple print (Misook: red with white hibiscus flowers; Deoksu: blue with white leaves; Kong: green with small yellow pineapples). Deoksu pulls a small rolling suitcase. On the right, a little apart from them, Dubu stands looking exhausted: she wears a thick puffy light gray padded winter jacket with quilted horizontal lines, THE BACKPACK on her back, and holds an open pale blue umbrella over her head even though the sun is shining. Her eyes are small half-closed dashes, her shoulders droop, and three short vertical gloom lines are drawn on her forehead. Everyone full body, in the lower 60% of the image; the upper 40% empty white.""" + END
cuts['cut6'] = """Additional characters (see the sheets and the lineup): Bamtol, a warm brown #C9A582 hedgehog, ONE solid color including the face, spikes drawn ONLY as a zigzag outline around the back of his head and body (no lines inside), small rounded ears, no tail, dot eyes, no mouth; slightly taller than Dubu. And one pink #F2C9CF cat with the same design as the cats sheet: small pointed triangular ears in the same flat pink, thin short tail, dot eyes, no mouth; same height as Dubu.
Scene: night in a dim room. At the bottom, Dubu lies on a simple flat mattress on the floor, covered up to her nose by a lumpy pale blue blanket; only the top of her head, her ears and her eyes show. Her eyes are squeezed tightly shut, drawn as two small scrunched wavy lines, one tear leaks from the corner of one eye, and the blanket lump is shaking: a few short curved tremble lines on both sides of the blanket. Above the bed floats one large fluffy cloud-shaped dream cloud with a soft rounded outline and a very light gray fill, with NO tail and NO small trailing circles. Inside the dream cloud: Bamtol walks arm in arm with the pink cat, both with closed-arc happy eyes, one small heart floating between them. Muted, desaturated colors except the heart. The dream cloud in the middle of the image, the bed at the bottom, the upper 35% empty white.""" + END
cuts['cut7'] = "Scene: Dubu marches forward toward the viewer in three-quarter view, determined (eyes as two small straight dashes), fully armed as if going to war although she is only walking to a convenience store: a small rectangular paper talisman stuck to her forehead (pale yellow paper with a few simple red brush squiggles, no readable letters), a flat gray metal chest armor with rounded shoulder pads over her body, a big round shield (gray with a terracotta #C77B3F rim) held up in one hand, THE BACKPACK on her back, a terracotta #C77B3F hero cape fluttering behind her from her shoulders, and a large transparent pale blue force-field bubble (a thin circle with a faint fill) drawn around her whole body. Bright, warm colors. No sparkles. Character in the lower 60% of the image, the upper 40% empty white." + END

import os
os.makedirs('prompts', exist_ok=True)
open('conti.md', 'w', encoding='utf-8', newline='\n').write(files['conti.md'])
open('prompts/_header.txt', 'w', encoding='utf-8', newline='\n').write(HEADER)
for k, v in cuts.items():
    open(f'prompts/{k}.txt', 'w', encoding='utf-8', newline='\n').write(HEADER + v)
print(sorted(os.listdir('prompts')))
